language: objective-c

xcode_project: UserDefaults.xcodeproj
xcode_scheme: UserDefaults-iOS

script:
  - xcodebuild clean build -sdk iphonesimulator -project UserDefaults.xcodeproj -scheme UserDefaults-iOS